function createfigure(xdata1, ydata1, zdata1, zdata2)
%CREATEFIGURE(xdata1, ydata1, zdata1, zdata2)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z
%  ZDATA2:  contour z

%  Auto-generated by MATLAB on 13-Oct-2022 14:48:12

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create contour
contour(xdata1,ydata1,zdata1,'DisplayName','Constrained GMM Projection',...
    'LineWidth',1.5,...
    'LineColor',[0 0 1],...
    'LevelList',[0.00651584802562201 0.013031696051244 0.019547544076866 0.026063392102488 0.03257924012811 0.039095088153732 0.0456109361793541 0.0521267842049761 0.0586426322305981 0.0651584802562201]);

% Create contour
contour(xdata1,ydata1,zdata2,'DisplayName','Original GMM','LineWidth',1.5,...
    'LineColor',[0 0 0],...
    'LevelList',[0.0104080080839623 0.0208160161679245 0.0312240242518868 0.041632032335849 0.0520400404198113 0.0624480485037736 0.0728560565877358 0.0832640646716981 0.0936720727556604 0.104080080839623]);

% Create ylabel
ylabel('Y','FontSize',14);

% Create xlabel
xlabel('X','FontSize',14);

% Create title
title('Constrained GMM Projection','FontSize',14);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-5.13059792425574 7.18519691328122]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-4.66071437139572 7.65508046614124]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'BoxStyle','full','Layer','top');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwest','FontSize',12);

