function createfigure(xvector1, ymatrix1)
%CREATEFIGURE(xvector1, ymatrix1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 13-Oct-2022 11:47:56

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'Parent',axes1);
set(bar1(5),'DisplayName','NA of True',...
    'CData',[0 0.447 0.741;0 0.447 0.741;0 0.447 0.741;0 0.447 0.741;0 0.447 0.741;0 0.447 0.741;0 0.447 0.741;0 0.447 0.741;0 0.447 0.741;0 0.447 0.741]);
set(bar1(4),'DisplayName','Direct Moment-matching',...
    'CData',[0.85 0.325 0.098;0.85 0.325 0.098;0.85 0.325 0.098;0.85 0.256582446808511 0;0.85 0.325 0.098;0.85 0.325 0.098;0.85 0.325 0.098;0.85 0.325 0.098;0.85 0.325 0.098;0.85 0.325 0.098]);
set(bar1(3),'DisplayName','Constrained MM',...
    'CData',[0.929 0.694 0.125;0.929 0.694 0.125;0.929 0.694 0.125;0.929 0.694 0.125;0.929 0.694 0.125;0.929 0.694 0.125;0.929 0.694 0.125;0.929 0.657463930348259 0;0.929 0.694 0.125;0.929 0.694 0.125]);
set(bar1(2),'DisplayName','NA of Constrained MM',...
    'CData',[0.494 0.184 0.556;0.494 0.184 0.556;0.494 0.184 0.556;0.494 0.184 0.556;0.494 0.184 0.556;0.494 0.184 0.556;0.494 0.184 0.556;0.494 0.184 0.556;0.494 0.184 0.556;0.463333333333334 0 0.556]);
set(bar1(1),'DisplayName','Jensen''s inequality',...
    'CData',[0.466 0.674 0.188;0.466 0.674 0.188;0.466 0.674 0.188;0.466 0.674 0.188;0.466 0.674 0.188;0.385539094650206 0.674 0;0.466 0.674 0.188;0.466 0.674 0.188;0.466 0.674 0.188;0.466 0.674 0.188]);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','\color[rgb]{black} \bf \diamondsuit',...
    'Position',[7.69230769230769 1.54340311508545 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','\color[rgb]{black} \bf \diamondsuit',...
    'Position',[3.84615384615385 1.58906729396371 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','\color[rgb]{black} \bf \diamondsuit',...
    'Position',[8 1.39080671954593 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','\color[rgb]{black} \bf \diamondsuit',...
    'Position',[10.1538461538462 1.28159450997596 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','\color[rgb]{black} \bf \diamondsuit',...
    'Position',[6.30769230769231 0.819764000300418 0]);

% Create ylabel
ylabel('MI estimation','FontSize',14);

% Create xlabel
xlabel('Tests','FontSize',14);

% Create title
title('Estimated MI','FontSize',14);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.507692337036133 10.4923076629639]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1.60000002384186]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XTick',[1 2 3 4 5 6 7 8 9 10]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',12);

